### ISSUE TITLE
Python3 support

### ISSUE THREAD

**Issue by florianib** [Rami114/cryptoscan#1]
Hey,

I wanted to use your plugin with the latest binja version, but I get an error that it cannot find the "module" folder.

Can you please update your plugin?

Thanks!

**Comment by Rami114** [comment]
@0x00xx sure can do, are you using it with the new Python 3 support or is it Python 2 still?

**Comment by florianib** [comment]
@Rami114 Wow that was a fast reply :)

I am using it with the python3 support

**Comment by Rami114** [comment]
Suspected as much, I'll have a go at switching to Python3 and will let you know.

**Comment by Rami114** [comment]
@0x00xx got it working on my local install (tested on Python2 and 3 now). Taught me something new about relative imports that did :) Can you let me know how you go?

**Comment by florianib** [comment]
Yeah, I read up on that, but didn't manage to fix it by myself :)

Works like a charm now, thanks for the update!
