### ISSUE TITLE
Update Plugin for Plugin Manager 2.0

### ISSUE THREAD

**Issue by plafosse** [Rami114/cryptoscan#3]
With the introduction of the Binary Ninja Plugin Manager 2.0 we will be releasing a installation UI for all plugins in the community repository. Please check https://binary.ninja/2019/07/04/plugin-manager-2.0.html for the latest information about how to submit your plugin. If you no longer want your plugin in the repository please disregard this issue

**Comment by Rami114** [comment]
opening my closet of skeletons that is github. This sounds like a fun project, so duly noted (only 1 year late).

**Comment by fuomag9** [comment]
I'd love to see this plugin added to the plugin manager!

**Comment by Rami114** [comment]
Booked some time in my own diary tomorrow to work on this. 🥂

**Comment by Rami114** [comment]
Updated and requested addition of plugin at https://github.com/Vector35/community-plugins/issues/118
